db:
    image: postgres:latest
    environment:
        POSTGRES_PASSWORD: django
        POSTGRES_USER: django
django:
    build: .
    volumes:
        - "src:/src"
    ports:
        - "8000:8000"
    links:
        - "db:db"
    environment:
        PYTHONUNBUFFERED: 1